[package]
name = "obj-alloc"
version = "0.1.1"
edition = "2024"
license = "Apache-2.0"
description = "自用 field-collex 可序列化K-V封装"
repository = "https://github.com/Milk-COCO/obj-alloc"

[dependencies]
field-collex = "0.0.10"
span-core = "0.1.1"
serde = "^1.0"
serde_json = "^1.0"